// ─────────────────────────────────────────────
// SYNAPSE — Project Exporter
// 1. Generates README.md via Groq
// 2. Creates package.json for the project
// 3. Packages everything into a .zip file
// ─────────────────────────────────────────────

const fs = require("fs");
const path = require("path");
const archiver = require("archiver");
const { callAI } = require("../services/aiRouter");
const db = require("../database/connection");
const log = require("../utils/logger");

const OUTPUT_DIR = path.join(__dirname, "..", "output");

// ── Generate README.md from project code ──

async function generateReadme(projectName, prompt, files) {
    log.step("EXPORT", "Generating README.md via Groq...");

    const fileList = files.map(f => `- ${f.filename} (${f.file_type}): ${f.explanation || "No description"}`).join("\n");

    const readmePrompt = `
You are a technical writer. Generate a professional README.md for a project.

PROJECT NAME: ${projectName}
ORIGINAL PROMPT: ${prompt}

FILES IN THIS PROJECT:
${fileList}

GENERATE A README.md WITH THESE SECTIONS:
1. # Project Name (formatted nicely)
2. ## Description — What this project does (2-3 sentences)
3. ## Tech Stack — List technologies used
4. ## Project Structure — Show the folder/file tree
5. ## Getting Started
   - Prerequisites (Node.js version, etc.)
   - Installation steps (npm install)
   - How to run the backend (node server.js)
   - How to run the frontend (explain Vite/React setup)
6. ## API Endpoints — List all routes with method, path, and description
7. ## Features — Bullet list of key features
8. ## Generated by SYNAPSE — A small footer note

OUTPUT ONLY THE README CONTENT. No extra commentary. Start with # immediately.
`;

    const readme = await callAI(readmePrompt, { task: "readme" });

    if (!readme || readme.trim().length === 0) {
        return `# ${projectName}\n\nGenerated by SYNAPSE.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnode server.js\n\`\`\`\n`;
    }

    return readme;
}

// ── Generate package.json for the exported project ──

function generatePackageJson(projectName, files) {
    // Detect dependencies from require() statements
    const deps = new Set();
    deps.add("express");
    deps.add("cors");

    files.forEach(f => {
        if (f.file_type === "backend" && f.code) {
            const requires = f.code.match(/require\(['"]([^./][^'"]*)['"]\)/g) || [];
            requires.forEach(r => {
                const mod = r.match(/require\(['"]([^'"]+)['"]\)/);
                if (mod && mod[1] && !mod[1].startsWith(".") && !mod[1].startsWith("node:")) {
                    deps.add(mod[1]);
                }
            });
        }
    });

    const depObj = {};
    deps.forEach(d => { depObj[d] = "latest"; });

    return JSON.stringify({
        name: projectName,
        version: "1.0.0",
        description: `Generated by SYNAPSE — ${projectName}`,
        main: "server.js",
        scripts: {
            start: "node server.js",
            dev: "nodemon server.js"
        },
        dependencies: depObj,
        keywords: [],
        author: "SYNAPSE AI",
        license: "MIT"
    }, null, 2);
}

// ── Create ZIP archive ──

async function createZip(projectName, files, readme, packageJson) {
    const exportDir = path.join(OUTPUT_DIR, projectName, "export");

    // Ensure export directory exists
    if (!fs.existsSync(exportDir)) {
        fs.mkdirSync(exportDir, { recursive: true });
    }

    const zipPath = path.join(exportDir, `${projectName}.zip`);

    return new Promise((resolve, reject) => {
        const output = fs.createWriteStream(zipPath);
        const archive = archiver("zip", { zlib: { level: 9 } });

        output.on("close", () => {
            log.success("EXPORT", `ZIP created: ${zipPath} (${archive.pointer()} bytes)`);
            resolve(zipPath);
        });

        archive.on("error", (err) => {
            log.error("EXPORT", `ZIP error: ${err.message}`);
            reject(err);
        });

        archive.pipe(output);

        // Add README.md
        archive.append(readme, { name: "README.md" });

        // Add package.json to backend
        archive.append(packageJson, { name: "backend/package.json" });

        // Add all generated files
        files.forEach(f => {
            const folder = f.file_type === "frontend" ? "frontend" : "backend";
            archive.append(f.code, { name: `${folder}/${f.filename}` });
        });

        archive.finalize();
    });
}

// ── Main Export Function ──

async function exportProject(projectId) {
    log.step("EXPORT", `Starting export for project ${projectId}`);

    // Step 1: Get project info
    const projects = await db.query(
        `SELECT * FROM projects WHERE id = ?`,
        [projectId]
    );

    if (!projects || projects.length === 0) {
        throw new Error(`Project ${projectId} not found`);
    }

    const project = projects[0];

    // Step 2: Get all generated files (with code)
    const files = await db.query(
        `SELECT filename, file_type, code, explanation FROM generated_files WHERE project_id = ?`,
        [projectId]
    );

    if (!files || files.length === 0) {
        throw new Error("No generated files found for this project");
    }

    log.info("EXPORT", `Found ${files.length} files for project: ${project.project_name}`);

    // Step 3: Generate README via Groq
    const readme = await generateReadme(project.project_name, project.prompt, files);

    // Step 4: Generate package.json
    const packageJson = generatePackageJson(project.project_name, files);

    // Step 5: Create ZIP
    const zipPath = await createZip(project.project_name, files, readme, packageJson);

    return {
        projectName: project.project_name,
        zipPath,
        filesCount: files.length,
        readmeGenerated: true
    };
}

module.exports = { exportProject, generateReadme, createZip, generatePackageJson };
