// ─────────────────────────────────────────────
// SYNAPSE — Reviewer Agent
// Phase 1: Rule-based validation (no AI call)
// Phase 2: AI-powered review (only if issues found)
// Uses same <FILE> format so parser can re-parse
// ─────────────────────────────────────────────

const callAI = require("../services/aiservice");
const { parseBatchOutput } = require("../utils/parser");
const log = require("../utils/logger");

// ── Phase 1: Rule-Based Validation ──

function validateFiles(tasks, files) {
    const issues = [];

    // Check: do we have any files at all?
    if (files.length === 0) {
        issues.push("No files were generated by executor");
        return issues;
    }

    // Check: any file has empty code?
    files.forEach(file => {
        if (!file.code || file.code.trim().length < 10) {
            issues.push(`Empty or too short code in: ${file.filename}`);
        }
    });

    // Check: backend .js files should have require/module.exports OR import/export
    files.forEach(file => {
        if (file.filename.endsWith(".js") && !file.filename.endsWith(".jsx")) {
            const hasRequire = file.code.includes("require(");
            const hasModuleExports = file.code.includes("module.exports");
            const hasImport = file.code.includes("import ");
            const hasExportDefault = file.code.includes("export default");
            const hasExportConst = file.code.includes("export const");
            const hasExportFunction = file.code.includes("export function");

            const hasAnyImport = hasRequire || hasImport;
            const hasAnyExport = hasModuleExports || hasExportDefault || hasExportConst || hasExportFunction;

            // Entry point files (server.js, index.js, App.js) and frontend files don't need exports
            const isEntryPoint = file.filename === "server.js" || file.filename === "index.js" || file.filename === "App.js";
            const isFrontend = file.filename.includes("components/") || file.filename.includes("pages/");

            if (!hasAnyImport && !isEntryPoint && !isFrontend) {
                issues.push(`${file.filename} — no import/require statements found`);
            }

            if (!hasAnyExport && !isEntryPoint && !isFrontend) {
                issues.push(`${file.filename} — no export/module.exports found`);
            }
        }
    });

    // Check: React files should have JSX return
    files.forEach(file => {
        if (file.filename.endsWith(".jsx")) {
            const hasReturn = file.code.includes("return");
            const hasJSXOpen = file.code.includes("<");

            if (!hasReturn || !hasJSXOpen) {
                issues.push(`${file.filename} — missing JSX return statement`);
            }
        }
    });

    // Check: did executor miss any planned files?
    const generatedNames = files.map(f => f.filename.toLowerCase());

    tasks.forEach(task => {
        const match = task.task.match(/[\w\-/]+\.(js|jsx)/i);

        if (match) {
            const expected = match[0].toLowerCase();

            if (!generatedNames.includes(expected)) {
                issues.push(`Missing file: ${match[0]} (planned but not generated)`);
            }
        }
    });

    return issues;
}

// ── Phase 2: AI-Powered Review ──

function buildReviewPrompt(files, issues) {
    const fileBlocks = files.map(f => {
        return `<FILE: ${f.filename}>
<CODE>
${f.code}
</CODE>
</FILE>`;
    }).join("\n\n");

    const issueList = issues.map((iss, i) => `${i + 1}. ${iss}`).join("\n");

    return `
You are a strict senior code reviewer. Fix and improve the code below.

ISSUES FOUND BY AUTOMATED SCAN:
${issueList}

YOUR TASK:
- Fix every issue listed above
- Fix any additional bugs (missing imports, broken logic, syntax errors)
- Keep the same file structure — do not add or remove files
- Make every file complete and production-ready
- Use require() and module.exports for backend .js files
- Use import/export for React .jsx files

OUTPUT FORMAT (follow EXACTLY — this is machine-parsed):

<FILE: filename.ext>
<EXPLANATION>
What you fixed or improved in this file
</EXPLANATION>
<CODE>
the complete corrected source code for this file
</CODE>
</FILE>

ABSOLUTE RULES — VIOLATION MEANS FAILURE:
- The <CODE> block must contain ONLY valid JavaScript/JSX source code
- Do NOT put explanations, numbered lists, or markdown inside <CODE> blocks
- Do NOT use backticks or code fences anywhere in your output
- Output ALL files even if unchanged — copy them exactly
- Every <CODE> block must start with actual code (const, import, require, function, etc.)
- The filename must exactly match the original filename
- Do NOT write anything outside <FILE> blocks

CODE BEING REVIEWED:

${fileBlocks}

Begin review output now. First line must be <FILE: ${files[0].filename}>
`;
}

// ── Main Reviewer Function ──

async function reviewerAgent(tasks, files) {
    log.step("REVIEWER", "Starting code review...");

    // Phase 1: rule-based checks
    const issues = validateFiles(tasks, files);

    if (issues.length === 0) {
        log.success("REVIEWER", "All rule checks passed — code looks clean");
        return { files, reviewed: false, issues: [] };
    }

    // Issues found — log them
    log.warn("REVIEWER", `Found ${issues.length} issue(s):`);

    issues.forEach(iss => {
        log.warn("REVIEWER", `  • ${iss}`);
    });

    // Phase 2: send to AI for fixes
    log.step("REVIEWER", "Sending to AI for review and fixes...");

    const reviewPrompt = buildReviewPrompt(files, issues);

    const raw = await callAI(reviewPrompt);

    if (!raw || raw.trim().length === 0) {
        log.error("REVIEWER", "AI returned empty — keeping original code");
        return { files, reviewed: true, issues };
    }

    const fixedFiles = parseBatchOutput(raw);

    if (fixedFiles.length === 0) {
        log.error("REVIEWER", "Could not parse AI review output — keeping original code");
        return { files, reviewed: true, issues };
    }

    // Verify the AI actually returned code (not explanations)
    const hasRealCode = fixedFiles.every(f => {
        const firstLine = f.code.split("\n")[0].trim();
        // Real code starts with: const, let, var, import, require, function, //, /*, export, 'use
        return /^(const |let |var |import |require|function |\/\/|\/\*|export |'use |"use )/.test(firstLine);
    });

    if (!hasRealCode) {
        log.warn("REVIEWER", "AI returned non-code content — keeping original code");
        return { files, reviewed: true, issues };
    }

    log.success("REVIEWER", `Review complete — ${fixedFiles.length} files fixed`);

    return { files: fixedFiles, reviewed: true, issues };
}

module.exports = reviewerAgent;
